# 1. Import Libraries

In [26]:
import sys
from pathlib import Path

root_dir = Path.cwd().parent
if str(root_dir) not in sys.path:
    sys.path.append(str(root_dir))

In [27]:
from Database.db_connector import DatabaseConnector
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from dotenv import load_dotenv, find_dotenv, dotenv_values

# 2. Load Data

In [28]:
db = DatabaseConnector()

In [29]:
print(db._engine)

None

In [31]:
fct_campaign_kpis = db.query("SELECT * FROM fct_campaign_kpis")
agg_brand_kpis = db.query("SELECT * FROM agg_brand_kpis")
agg_campaign_type_kpis = db.query("SELECT * FROM agg_campaign_type_kpis")
agg_monthly_kpis = db.query("SELECT * FROM agg_monthly_kpis")

In [32]:
fct_campaign_kpis.head()

,Campaign_ID,Brand,Campaign_Type,Language,Customer_Segment,Target_Audience,Duration,Campaign_Date,campaign_month,Impressions,...,CPA,calc_total_spend,calc_profit,calc_ctr,calc_lead_rate,calc_lead_conversion_rate,calc_cvr,calc_aov,calc_roi,campaign_status
0,NY-CMP-1000,Nykaa,Social Media,Hindi,College Students,College Students,21,2025-04-29,2025-04,57804,...,111.03,261475.65,1606039.35,0.1065,0.5874,0.6513,0.3826,793.0,6.1422,SCALE
1,NY-CMP-10000,Nykaa,Social Media,English,Working Women,Working Women,19,2024-08-04,2024-08,10767,...,655.46,98974.46,-31779.46,0.0516,0.5396,0.5033,0.2716,445.0,-0.3211,STOP
2,NY-CMP-10001,Nykaa,Paid Ads,Tamil,Premium Shoppers,Premium Shoppers,14,2024-07-27,2024-07,19243,...,761.58,212480.82,-111482.82,0.0497,0.4754,0.6132,0.2915,362.0,-0.5247,STOP
3,NY-CMP-10002,Nykaa,Paid Ads,Bengali,Tier 2 City Customers,Youth,18,2024-08-01,2024-08,94007,...,24.67,71888.38,1253981.62,0.0749,0.5645,0.7329,0.4137,455.0,17.4435,SCALE
4,NY-CMP-10003,Nykaa,Email,Tamil,Premium Shoppers,Tier 2 City Customers,27,2025-04-28,2025-04,15135,...,1035.04,134555.20,-69815.20,0.0459,0.3568,0.5242,0.1871,498.0,-0.5189,STOP

In [33]:
agg_brand_kpis

,Brand,total_campaigns,total_revenue,total_spend,total_profit,overall_ctr,overall_lead_rate,overall_conv_rate,overall_cvr,overall_cpa,overall_roi,scale_count,watch_count,stop_count
0,Nykaa,55175,2.845542e+10,9.631785e+09,1.882363e+10,0.0851,0.4003,0.5503,0.2203,169.01,1.9543,35301.0,6686.0,13188.0
1,Purplle,55175,2.834670e+10,9.651959e+09,1.869474e+10,0.0850,0.3994,0.5498,0.2196,170.12,1.9369,35253.0,6657.0,13265.0
2,Tira Beauty,55175,2.825120e+10,9.647897e+09,1.860330e+10,0.0850,0.3992,0.5495,0.2193,170.47,1.9282,35259.0,6916.0,13000.0

In [35]:
agg_campaign_type_kpis

,Campaign_Type,total_campaigns,total_revenue,total_spend,total_profit,overall_ctr,overall_lead_rate,overall_conv_rate,overall_cvr,overall_cpa,overall_roi,scale_count,watch_count,stop_count
0,Social Media,32982,1.701458e+10,5.758375e+09,1.125620e+10,0.0853,0.4001,0.5491,0.2197,168.68,1.9548,21122.0,4166.0,7694.0
1,Paid Ads,33060,1.710169e+10,5.779168e+09,1.132253e+10,0.0850,0.3993,0.5503,0.2197,169.54,1.9592,21258.0,4018.0,7784.0
2,Email,33244,1.710623e+10,5.810489e+09,1.129575e+10,0.0850,0.4001,0.5508,0.2204,169.70,1.9440,21288.0,3951.0,8005.0
3,Influencer,33278,1.695624e+10,5.822350e+09,1.113390e+10,0.0852,0.3991,0.5494,0.2193,170.75,1.9123,21169.0,4067.0,8042.0
4,SEO,32961,1.687457e+10,5.761258e+09,1.111331e+10,0.0847,0.3996,0.5499,0.2197,170.65,1.9290,20976.0,4057.0,7928.0

In [36]:
agg_monthly_kpis

,campaign_month,total_campaigns,total_revenue,total_spend,total_profit,overall_ctr,overall_lead_rate,overall_conv_rate,overall_cvr,overall_cpa,overall_roi,scale_count,watch_count,stop_count
0,2025-04,14478,7.290159e+09,2.527032e+09,4.763127e+09,0.0842,0.3997,0.5473,0.2187,172.58,1.8849,9248.0,1720.0,3510.0
1,2024-08,14902,7.710153e+09,2.622118e+09,5.088035e+09,0.0853,0.4003,0.5492,0.2198,169.95,1.9404,9459.0,1846.0,3597.0
2,2024-07,14787,7.693411e+09,2.579928e+09,5.113484e+09,0.0857,0.4002,0.5500,0.2201,167.75,1.9820,9482.0,1828.0,3477.0
3,2024-12,14856,7.664220e+09,2.592664e+09,5.071556e+09,0.0848,0.3996,0.5519,0.2206,169.35,1.9561,9516.0,1777.0,3563.0
4,2025-02,13466,6.992596e+09,2.348009e+09,4.644588e+09,0.0855,0.4015,0.5523,0.2217,166.84,1.9781,8624.0,1684.0,3158.0
5,2024-09,14391,7.335001e+09,2.518870e+09,4.816131e+09,0.0846,0.3984,0.5514,0.2197,171.78,1.9120,9154.0,1744.0,3493.0
6,2025-01,14739,7.611721e+09,2.578389e+09,5.033332e+09,0.0849,0.3999,0.5493,0.2197,169.99,1.9521,9469.0,1791.0,3479.0
7,2024-11,14331,7.360320e+09,2.507094e+09,4.853226e+09,0.0850,0.3996,0.5514,0.2203,169.48,1.9358,9158.0,1726.0,3447.0
8,2025-06,5427,2.752074e+09,9.371412e+08,1.814933e+09,0.0843,0.4003,0.5423,0.2171,169.84,1.9367,3525.0,675.0,1227.0
9,2024-10,14821,7.608699e+09,2.602872e+09,5.005827e+09,0.0853,0.3977,0.5490,0.2183,170.74,1.9232,9488.0,1773.0,3560.0
10,2025-03,14479,7.461042e+09,2.530612e+09,4.930431e+09,0.0853,0.4009,0.5494,0.2202,169.44,1.9483,9204.0,1851.0,3424.0
11,2025-05,14848,7.573919e+09,2.586912e+09,4.987007e+09,0.0853,0.3983,0.5504,0.2192,170.56,1.9278,9486.0,1844.0,3518.0

# 3. Overview

In [37]:
total_revenue_3_shop = sum(agg_brand_kpis["total_revenue"])
total_spend_3_shop = sum(agg_brand_kpis["total_spend"])
total_profit_3_shop = sum(agg_brand_kpis["total_profit"])
total_campaign_3_shop = sum(agg_brand_kpis["total_campaigns"])
total_weighted_roi_3_shop = (total_revenue_3_shop - total_spend_3_shop)/total_spend_3_shop

In [38]:
dict_overview = {
    "Total Revenue": total_revenue_3_shop,
    "Total Spend": total_spend_3_shop,
    "Total profit": total_profit_3_shop,
    "Total Campaign": total_campaign_3_shop,
    "Total Weighted ROI": total_weighted_roi_3_shop
}

pd.DataFrame(dict_overview, index = [0])

,Total Revenue,Total Spend,Total profit,Total Campaign,Total Weighted ROI
0,8.505332e+10,2.893164e+10,5.612168e+10,165525,1.939803